project:
  type: book
  output-dir: "docs"


website:
  favicon: img/logos/favicon.ico
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Manual de Análisis Matemático Real"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "manual-analisis"
  image: cover.png
  cover-image: img/logos/pi.jpg
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - teoria-conjuntos.qmd
    - cuerpo-reales.qmd
    - topologia-reales.qmd
    #- sucesiones.qmd
    #- limites.qmd
    
#bibliography: references.bib


format:
  html:
    theme: cosmo
    dark: darkly
    light: flatly
  pdf:
    documentclass: scrreport
    include-in-header:
      - macros.tex
  epub:
    cover-image: img/logos/pi.jpg



